/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/healthz": {
    /** Healthz */
    get: operations["routes_api_healthz"];
  };
  "/v1/tipo": {
    /** Producao Bibliografica Tipo */
    get: operations["routes_api_producao_bibliografica_tipo"];
  };
  "/v1/campus": {
    /** Get Campuses */
    get: operations["routes_api_get_campuses"];
  };
  "/v1/grande_area": {
    /** Get Grande Areas */
    get: operations["routes_api_get_grande_areas"];
  };
  "/v1/area": {
    /** Get Areas */
    get: operations["routes_api_get_areas"];
  };
  "/v1/atuacoes/stats": {
    /** Stats */
    get: operations["routes_atuacoes_stats"];
  };
  "/v1/formacoes/stats": {
    /** Stats */
    get: operations["routes_formacoes_stats"];
  };
  "/v1/producoes_bibliograficas": {
    /** List */
    get: operations["routes_producoes_bibliograficas_list"];
  };
  "/v1/producoes_bibliograficas/stats": {
    /** Stats */
    get: operations["routes_producoes_bibliograficas_stats"];
  };
  "/v1/pesquisadores/{siape}/areas_conhecimento": {
    /** Areas Conhecimento */
    get: operations["routes_pesquisadores_areas_conhecimento"];
  };
  "/v1/pesquisadores/{siape}/palavras_chave": {
    /** Palavras Chave */
    get: operations["routes_pesquisadores_palavras_chave"];
  };
  "/v1/pesquisadores": {
    /** Search Researcher */
    get: operations["routes_pesquisadores_search_researcher"];
  };
  "/v1/pesquisadores/{siape}": {
    /** Get Pesquisador */
    get: operations["routes_pesquisadores_get_pesquisador"];
  };
  "/v1/pesquisadores/{siape}/producoes": {
    /** List Producoes Bibliograficas */
    get: operations["routes_pesquisadores_list_producoes_bibliograficas"];
  };
  "/v1/pesquisadores/{siape}/producoes/stats": {
    /** Stats Producoes Bibliograficas */
    get: operations["routes_pesquisadores_stats_producoes_bibliograficas"];
  };
  "/v1/pesquisadores/{siape}/producoes/graph": {
    /** Graph Producoes Bibliograficas */
    get: operations["routes_pesquisadores_graph_producoes_bibliograficas"];
  };
  "/v1/pesquisadores/{siape}/formacoes": {
    /** Stats Formacao */
    get: operations["routes_pesquisadores_stats_formacao"];
  };
  "/v1/pesquisadores/{siape}/formacoes/graph": {
    /** Graph Formacao */
    get: operations["routes_pesquisadores_graph_formacao"];
  };
  "/v1/pesquisadores/{siape}/producoes_tecnicas": {
    /** List Producoes Tecnicas */
    get: operations["routes_pesquisadores_list_producoes_tecnicas"];
  };
  "/v1/pesquisadores/{siape}/producoes_tecnicas/stats": {
    /** Stats Producoes Tecnicas */
    get: operations["routes_pesquisadores_stats_producoes_tecnicas"];
  };
  "/v1/pesquisadores/{siape}/producoes_tecnicas/graph": {
    /** Graph Producoes Tecnicas */
    get: operations["routes_pesquisadores_graph_producoes_tecnicas"];
  };
  "/v1/pesquisadores/{siape}/bancas": {
    /** List Bancas */
    get: operations["routes_pesquisadores_list_bancas"];
  };
  "/v1/pesquisadores/{siape}/bancas/stats": {
    /** Stats Bancas */
    get: operations["routes_pesquisadores_stats_bancas"];
  };
  "/v1/pesquisadores/{siape}/bancas/graph": {
    /** Graph Bancas */
    get: operations["routes_pesquisadores_graph_bancas"];
  };
  "/v1/pesquisadores/{siape}/projetos_pesquisa": {
    /** List Projetos Pesquisa */
    get: operations["routes_pesquisadores_list_projetos_pesquisa"];
  };
  "/v1/pesquisadores/{siape}/projetos_pesquisa/stats": {
    /** Stats Projetos Pesquisa */
    get: operations["routes_pesquisadores_stats_projetos_pesquisa"];
  };
  "/v1/pesquisadores/{siape}/projetos_pesquisa/graph": {
    /** Graph Projetos Pesquisa */
    get: operations["routes_pesquisadores_graph_projetos_pesquisa"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** CurriculoReducedSchema */
    CurriculoReducedSchema: {
      /** Siape */
      siape?: string | null;
      /** Nome */
      nome: string;
      /** Cnpq */
      cnpq?: string | null;
    };
    /** ProducaoBibliograficaSchema */
    ProducaoBibliograficaSchema: {
      curriculo?: components["schemas"]["CurriculoReducedSchema"] | null;
      /** ID */
      id?: number | null;
      /** Doi */
      doi?: string | null;
      /** Natureza */
      natureza: string;
      /** Ano */
      ano?: string | null;
      /** Idioma */
      idioma?: string | null;
      /** Tipo */
      tipo?: string | null;
      /** Tipo Livro */
      tipo_livro?: string | null;
      /** Titulo */
      titulo: string;
      /** Classificacao */
      classificacao?: string | null;
      /** Meio Divulgacao */
      meio_divulgacao?: string | null;
      /** Palavras Chave */
      palavras_chave?: unknown[] | null;
      /** Revista */
      revista: number;
      /** Conferencia */
      conferencia: number;
      /** Areas Conhecimento */
      areas_conhecimento: number[];
      /** Autores */
      autores: number[];
    };
    /** Schema[ProducaoBibliograficaSchema] */
    Schema_ProducaoBibliograficaSchema_: {
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Results */
      results: components["schemas"]["ProducaoBibliograficaSchema"][];
    };
    /** ProducaoBiblioGraficaListQuery */
    ProducaoBiblioGraficaListQuery: {
      /** Campus */
      campus?: string | null;
      /** Grande Area */
      grande_area?: string | null;
      /** Area */
      area?: string | null;
      /**
       * Tipos
       * @default []
       */
      tipos?: string[];
      /** Ano Lte */
      ano_lte?: number | null;
      /** Ano Gte */
      ano_gte?: number | null;
    };
    /** ProducaoBibliograficaStatsResponse */
    ProducaoBibliograficaStatsResponse: {
      /** Ano */
      ano?: string | null;
      /** Qualis */
      qualis?: string | null;
      /** Grande Area */
      grande_area?: string | null;
      /** Tipo */
      tipo?: string | null;
      /** Total */
      total: number;
    };
    /** ProfessorAreasConhecimentoResponse */
    ProfessorAreasConhecimentoResponse: {
      /** Grandes Areas */
      grandes_areas: string[];
      /** Areas */
      areas: string[];
      /** Subareas */
      subareas: string[];
      /** Especialidades */
      especialidades: string[];
    };
    /** CurriculoSchema */
    CurriculoSchema: {
      /** Siape */
      siape?: string | null;
      /** Nome */
      nome: string;
      /** Cnpq */
      cnpq?: string | null;
      /** Citacoes */
      citacoes?: unknown[] | null;
      /** Resumo Cv */
      resumo_cv?: string | null;
    };
    /** GraphCurriculo */
    GraphCurriculo: {
      /**
       * Node
       * @default Curriculo
       * @constant
       * @enum {string}
       */
      node?: "Curriculo";
      /** Id */
      id: string;
      /** Siape */
      siape: string;
      /** Cnpq */
      cnpq: string;
      /** Nome */
      nome: string;
      /** Campus */
      campus: string;
      /** Categoria */
      categoria: string;
    };
    /** GraphLink */
    GraphLink: {
      /** Rel */
      rel: string;
      /** Id */
      id: string;
      /** Source */
      source: string;
      /** Target */
      target: string;
    };
    /** GraphProducaoBibliografica */
    GraphProducaoBibliografica: {
      /**
       * Node
       * @default ProducaoBibliografica
       * @constant
       * @enum {string}
       */
      node?: "ProducaoBibliografica";
      /** Id */
      id: string;
      /** Titulo */
      titulo: string;
      /** Ano */
      ano: string;
      /** Tipo */
      tipo: string;
      /** Tipo Livro */
      tipo_livro?: string | null;
    };
    /** GraphResponse[Union[GraphCurriculo, GraphProducaoBibliografica]] */
    GraphResponse_Union_GraphCurriculo__GraphProducaoBibliografica__: {
      /** Nodes */
      nodes: (components["schemas"]["GraphCurriculo"] | components["schemas"]["GraphProducaoBibliografica"])[];
      /** Links */
      links: components["schemas"]["GraphLink"][];
    };
    /** CursoSchema */
    CursoSchema: {
      /** ID */
      id?: number | null;
      /** Nome */
      nome?: string | null;
      /** Codigo */
      codigo?: string | null;
    };
    /** FormacaoAcademicaSchema */
    FormacaoAcademicaSchema: {
      instituicao: components["schemas"]["InstituicaoSchema"];
      curso: components["schemas"]["CursoSchema"];
      /** ID */
      id?: number | null;
      /** Ano Inicio */
      ano_inicio: string;
      /** Ano Conclusao */
      ano_conclusao?: string | null;
      /** Status */
      status: string;
      /** Tipo */
      tipo: string;
      /** Palavras Chave */
      palavras_chave?: unknown[] | null;
      /** Curriculo */
      curriculo: number;
      /** Areas Conhecimento */
      areas_conhecimento: number[];
    };
    /** InstituicaoSchema */
    InstituicaoSchema: {
      /** ID */
      id?: number | null;
      /** Nome */
      nome?: string | null;
      /** Codigo */
      codigo?: string | null;
    };
    /** GraphCurso */
    GraphCurso: {
      /**
       * Node
       * @default Curso
       * @constant
       * @enum {string}
       */
      node?: "Curso";
      /** Id */
      id: string;
      /** Nome */
      nome: string;
      /** Codigo */
      codigo?: string | null;
    };
    /** GraphResponse[Union[GraphCurriculo, GraphCurso]] */
    GraphResponse_Union_GraphCurriculo__GraphCurso__: {
      /** Nodes */
      nodes: (components["schemas"]["GraphCurriculo"] | components["schemas"]["GraphCurso"])[];
      /** Links */
      links: components["schemas"]["GraphLink"][];
    };
    /** ProducaoTecnicaSchema */
    ProducaoTecnicaSchema: {
      curriculo?: components["schemas"]["CurriculoReducedSchema"] | null;
      /** ID */
      id?: number | null;
      /** Titulo */
      titulo: string;
      /** Natureza */
      natureza?: string | null;
      /** Ano */
      ano?: string | null;
      /** Finalidade */
      finalidade?: string | null;
      /** Descricao */
      descricao?: string | null;
      /** Palavras Chave */
      palavras_chave?: unknown[] | null;
      /** Registro */
      registro?: number | null;
      /** Autores */
      autores: number[];
      /** Areas Conhecimento */
      areas_conhecimento: number[];
    };
    /** ProducaoTecnincaStatsResponse */
    ProducaoTecnincaStatsResponse: {
      /** Ano */
      ano: string;
      /** Natureza */
      natureza: string;
      /** Total */
      total: number;
    };
    /** GraphProducaoTecnica */
    GraphProducaoTecnica: {
      /**
       * Node
       * @default ProducaoTecnica
       * @constant
       * @enum {string}
       */
      node?: "ProducaoTecnica";
      /** Id */
      id: string;
      /** Titulo */
      titulo: string;
      /** Ano */
      ano: string;
      /** Natureza */
      natureza: string;
      /** Finalidade */
      finalidade: string;
    };
    /** GraphResponse[Union[GraphCurriculo, GraphProducaoTecnica]] */
    GraphResponse_Union_GraphCurriculo__GraphProducaoTecnica__: {
      /** Nodes */
      nodes: (components["schemas"]["GraphCurriculo"] | components["schemas"]["GraphProducaoTecnica"])[];
      /** Links */
      links: components["schemas"]["GraphLink"][];
    };
    /** BancaSchema */
    BancaSchema: {
      /** ID */
      id?: number | null;
      /** Titulo */
      titulo: string;
      /** Ano */
      ano?: string | null;
      /** Natureza */
      natureza?: string | null;
      /** Participantes */
      participantes: number[];
    };
    /** BancaStatsResponse */
    BancaStatsResponse: {
      /** Ano */
      ano: string;
      /** Natureza */
      natureza: string;
      /** Total */
      total: number;
    };
    /** GraphBanca */
    GraphBanca: {
      /**
       * Node
       * @default Banca
       * @constant
       * @enum {string}
       */
      node?: "Banca";
      /** Id */
      id: string;
      /** Titulo */
      titulo: string;
      /** Ano */
      ano: string;
      /** Natureza */
      natureza: string;
    };
    /** GraphResponse[Union[GraphCurriculo, GraphBanca]] */
    GraphResponse_Union_GraphCurriculo__GraphBanca__: {
      /** Nodes */
      nodes: (components["schemas"]["GraphCurriculo"] | components["schemas"]["GraphBanca"])[];
      /** Links */
      links: components["schemas"]["GraphLink"][];
    };
    /** ProjetoPesquisaSchema */
    ProjetoPesquisaSchema: {
      /** ID */
      id?: number | null;
      /** Nome */
      nome: string;
      /** Descricao */
      descricao?: string | null;
      /** Ano Inicio */
      ano_inicio?: string | null;
      /** Ano Fim */
      ano_fim?: string | null;
      /** Situacao */
      situacao?: string | null;
      /** Natureza */
      natureza?: string | null;
      /** Orgao */
      orgao?: number | null;
      /** Unidade */
      unidade?: number | null;
      /** Financiadores */
      financiadores: number[];
      /** Integrantes */
      integrantes: number[];
    };
    /** ProjetoPesquisaStatsResponse */
    ProjetoPesquisaStatsResponse: {
      /** Ano */
      ano: string;
      /** Natureza */
      natureza: string;
      /** Total */
      total: number;
    };
    /** GraphProjetoPesquisa */
    GraphProjetoPesquisa: {
      /**
       * Node
       * @default ProjetoPesquisa
       * @constant
       * @enum {string}
       */
      node?: "ProjetoPesquisa";
      /** Id */
      id: string;
      /** Natureza */
      natureza: string;
      /** Nome */
      nome: string;
      /** Ano Inicio */
      ano_inicio: string;
      /** Ano Fim */
      ano_fim: string;
    };
    /** GraphResponse[Union[GraphCurriculo, GraphProjetoPesquisa]] */
    GraphResponse_Union_GraphCurriculo__GraphProjetoPesquisa__: {
      /** Nodes */
      nodes: (components["schemas"]["GraphCurriculo"] | components["schemas"]["GraphProjetoPesquisa"])[];
      /** Links */
      links: components["schemas"]["GraphLink"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Healthz */
  routes_api_healthz: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Producao Bibliografica Tipo */
  routes_api_producao_bibliografica_tipo: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Get Campuses */
  routes_api_get_campuses: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Get Grande Areas */
  routes_api_get_grande_areas: {
    parameters: {
      query?: {
        campus?: string | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Get Areas */
  routes_api_get_areas: {
    parameters: {
      query?: {
        campus?: string | null;
        grande_area?: string | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /** Stats */
  routes_atuacoes_stats: {
    parameters: {
      query?: {
        campus?: string | null;
        ano?: string | null;
        area?: string | null;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  /** Stats */
  routes_formacoes_stats: {
    parameters: {
      query?: {
        campus?: string | null;
        ano?: string | null;
        area?: string | null;
        exibir_por?: "data" | "categoria";
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  /** List */
  routes_producoes_bibliograficas_list: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ProducaoBiblioGraficaListQuery"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Schema_ProducaoBibliograficaSchema_"];
        };
      };
    };
  };
  /** Stats */
  routes_producoes_bibliograficas_stats: {
    parameters: {
      query?: {
        campus?: string | null;
        grande_area?: string | null;
        area?: string | null;
        kind?: "tipo" | "qualis";
        display_by?: "data" | "categoria";
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProducaoBibliograficaStatsResponse"][];
        };
      };
    };
  };
  /** Areas Conhecimento */
  routes_pesquisadores_areas_conhecimento: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProfessorAreasConhecimentoResponse"];
        };
      };
    };
  };
  /** Palavras Chave */
  routes_pesquisadores_palavras_chave: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Search Researcher */
  routes_pesquisadores_search_researcher: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        query?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** Get Pesquisador */
  routes_pesquisadores_get_pesquisador: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CurriculoSchema"];
        };
      };
    };
  };
  /** List Producoes Bibliograficas */
  routes_pesquisadores_list_producoes_bibliograficas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProducaoBibliograficaSchema"][];
        };
      };
    };
  };
  /** Stats Producoes Bibliograficas */
  routes_pesquisadores_stats_producoes_bibliograficas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProducaoBibliograficaStatsResponse"][];
        };
      };
    };
  };
  /** Graph Producoes Bibliograficas */
  routes_pesquisadores_graph_producoes_bibliograficas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GraphResponse_Union_GraphCurriculo__GraphProducaoBibliografica__"];
        };
      };
    };
  };
  /** Stats Formacao */
  routes_pesquisadores_stats_formacao: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["FormacaoAcademicaSchema"][];
        };
      };
    };
  };
  /** Graph Formacao */
  routes_pesquisadores_graph_formacao: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GraphResponse_Union_GraphCurriculo__GraphCurso__"];
        };
      };
    };
  };
  /** List Producoes Tecnicas */
  routes_pesquisadores_list_producoes_tecnicas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProducaoTecnicaSchema"][];
        };
      };
    };
  };
  /** Stats Producoes Tecnicas */
  routes_pesquisadores_stats_producoes_tecnicas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProducaoTecnincaStatsResponse"][];
        };
      };
    };
  };
  /** Graph Producoes Tecnicas */
  routes_pesquisadores_graph_producoes_tecnicas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GraphResponse_Union_GraphCurriculo__GraphProducaoTecnica__"];
        };
      };
    };
  };
  /** List Bancas */
  routes_pesquisadores_list_bancas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["BancaSchema"][];
        };
      };
    };
  };
  /** Stats Bancas */
  routes_pesquisadores_stats_bancas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["BancaStatsResponse"][];
        };
      };
    };
  };
  /** Graph Bancas */
  routes_pesquisadores_graph_bancas: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GraphResponse_Union_GraphCurriculo__GraphBanca__"];
        };
      };
    };
  };
  /** List Projetos Pesquisa */
  routes_pesquisadores_list_projetos_pesquisa: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProjetoPesquisaSchema"][];
        };
      };
    };
  };
  /** Stats Projetos Pesquisa */
  routes_pesquisadores_stats_projetos_pesquisa: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProjetoPesquisaStatsResponse"][];
        };
      };
    };
  };
  /** Graph Projetos Pesquisa */
  routes_pesquisadores_graph_projetos_pesquisa: {
    parameters: {
      path: {
        siape: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GraphResponse_Union_GraphCurriculo__GraphProjetoPesquisa__"];
        };
      };
    };
  };
}
